services:
  - type: web
    name: dev-duel-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: true

  - type: web
    name: dev-duel-client
    env: node
    rootDir: client
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist/client
    plan: free
    autoDeploy: true
