services:
  - type: web
    name: dev-duel-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    autoDeploy: true

  - type: web
    name: dev-duel-client
    rootDir: client
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist/dev-duel
    autoDeploy: true
